//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models.StokEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTestStokEntities : DbContext
    {
        public DbTestStokEntities()
            : base("name=DbTestStokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StokKategori> StokKategori { get; set; }
        public virtual DbSet<StokMusteriBilgi> StokMusteriBilgi { get; set; }
        public virtual DbSet<StokSatis> StokSatis { get; set; }
        public virtual DbSet<StokSatislar> StokSatislar { get; set; }
        public virtual DbSet<StokUrunlerr> StokUrunlerr { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
