//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models.StokEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokUrunlerr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StokUrunlerr()
        {
            this.StokSatislar = new HashSet<StokSatislar>();
        }
    
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public int UrunKategori { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Stok { get; set; }
        public string Marka { get; set; }
    
        public virtual StokKategori StokKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokSatislar> StokSatislar { get; set; }
    }
}
