//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models.StokEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKullaniciGirisi
    {
        public int ID { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
    }
}
