//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test3.Models.StokEntity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class StokMusteriBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StokMusteriBilgi()
        {
            this.StokSatislar = new HashSet<StokSatislar>();
        }
    
        public int MusteriID { get; set; }

        [Required(ErrorMessage ="Bu Alaný Doldurmadýnýz")]
        [StringLength(50,ErrorMessage ="En fazla 50 Kareker Kullanabilirsiniz")]
        public string MusteriAd { get; set; }
        [Required(ErrorMessage = "Bu Alaný Doldurmadýnýz")]
        [StringLength(50, ErrorMessage = "En fazla 50 Kareker Kullanabilirsiniz")]
        public string MusteriSoyad { get; set; }
        [Required(ErrorMessage = "Bu Alaný Doldurmadýnýz")]
        [StringLength(50, ErrorMessage = "En fazla 50 Kareker Kullanabilirsiniz")]
        public string MusteriAdres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokSatislar> StokSatislar { get; set; }
    }
}
